server:
  port: 1111

spring:
  datasource:
    username: root
    password: Marko-2024
    url: jdbc:mysql://localhost:3306/pet_store_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB